#!/bin/sh
# $Id: initheaders 8 2011-04-03 10:47:38Z mzbjyza2mji4zgz $

if test ! -r ./configure.ac; then
    exit 1
fi

cd ./src/include/nata || exit 1

out=./.headers
rm -f ${out}
> ${out}

echo -n "HEADERS = " >> ${out}
for i in `ls *.h`; do
    echo ${i} | awk '{ printf("\\\n\t%s ", $1); }' >> ${out}
done

exit 0


